version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-34
    environment:
      JVM_OPTS: "-Xmx3g"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Install Dependencies
          command: |
            sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: app-debug.apk